# triggered by schedule
trigger: none
pr: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - main
  always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/pre-release.yml@templates
  parameters:
    usePreReleaseChannel: false
    l10nShouldProcess: false
    buildSteps:
      - checkout: self
        clean: true
        persistCredentials: true
      - bash: |
          npm install

          chmod +x ./build/updateGrammar.sh
          ./build/updateGrammar.sh
          grammarResult=$?
          if [ $grammarResult -neq 0 ] ; then
              echo "Unexpected error while updating grammar"
              exit $grammarResult
          fi

          npm run bump-version
          result=$?
          
          set -e
          if [ $result -eq 0 ]; then
            git config --local user.name "Azure Pipelines"
            git config --local user.email "azuredevops@microsoft.com"
            git add .
            git commit -m "Publishing version bump ***NO_CI***"
            git push origin HEAD:main

            exit
          elif [ $result -eq 1 ]; then
              echo "Skipping publish"
              exit 1
          else
              echo "Unexpected error"
              exit $result
          fi
        displayName: 'Update TypeScript and grammar'
