# triggered by schedule
trigger: none
pr: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - main
  always: true

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/pre-release.yml@templates
  parameters:
    usePreReleaseChannel: false
    buildSteps:
      - displayName: 'Update TypeScript and grammar'
        bash: |
          chmod +x ./build/updateGrammar.sh
          ./build/updateGrammar.sh
          grammarResult=$?
          if [ $grammarResult -neq 0 ] ; then
              echo "Unexpected error while updating grammar"
              exit $grammarResult
          fi

          npm run bump-version
          result=$?
          
          set -e
          if [ $result -eq 0 ]; then
            git config --local user.name "Azure Pipelines"
            git config --local user.email "azuredevops@microsoft.com"
            git add .
            git commit -m "Publishing version bump ***NO_CI***"

            mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
            chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            git remote set-url --push origin git@github.com:microsoft/vscode-typescript-next.git
            git push origin HEAD:main

            exit
          elif [ $result -eq 1 ]; then
              echo "Skipping publish"
              exit
          else
              echo "Unexpected error"
              exit $result
          fi
